👷 Heroku push

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -108,6 +108,30 @@ jobs:
             - venv
           key: v7-dependencies-{{ checksum "requirements/dev.txt" }}
 
+  back-deploy-heroku:
+    docker:
+      - image: buildpack-deps:trusty
+    steps:
+      - checkout
+      
+      - run:
+          name: Heroku Deploy
+          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
+
+      - run:
+          name: Heroku db upgrade
+          command: heroku run:detached flask db upgrade
+
+      - run:
+          name: Smoke Test
+          command: |
+            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/api/articles`
+            if [ "$HTTPCODE" -ne 200 ]; then
+              echo "heroku app not responding, failing deploy"
+              exit 1
+            fi
+
+
 workflows:
   version: 2
   build-test-and-deploy:
@@ -116,3 +140,6 @@ workflows:
       - test:
           requires:
             - build
+      - back-deploy-heroku:
+          requires :
+            - test
